name: Deploy
on: [push] # tells github to run this on any push to the repository
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # we tell Github to only execute this step if we're on our master branch (so we don't put unfinished branches in production)
    steps:
      - name: Deploying to server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd ~/orbita-challenge-full-stack-web
            git pull
            cd ~/orbita-challenge-full-stack-web/Backend/OrbitaChallenge.API
            pm2 delete dotnet
            pm2 start "dotnet run" --name dotnet
